### PR TITLE
[FLINK-23284] Reset the TARGET_COUNT_REACHED_LATCH before each execution of the job

### PR DESCRIPTION
**Pull request by dawidwys**

### CODE REVIEW

**Review by pnowojski — COMMENTED** [review]
What was the issue? That the latch was being reseted once per iteration instead of invocation? Where iteration is one or more invocations? And this latch was effectively working only for the first invocation? If so:

1. What about keeping `tearDown()` method but just using `Level.Invocation`?
2. Add this explanation to the commit message?

**Comment by pnowojski** [comment]
On a second thought. After reading all of the warnings around `Level.Invocation` I'm actually fine with the current approach. `Level.Invocation` is scary.

**Comment by dawidwys** [comment]
Generally speaking I don't know JMH enough to make a good judgement why was it so. I don't know how the `Levels` work and if 1. is enough :(  Why do you prefer using the `tearDown` method? I doubt calling the `reset` inside the benchmarked method introduces significant time penalty.

**Comment by dawidwys** [comment]
BTW, frankly speaking, the `Level.Iteration` should be enough from the javadoc, but apparently it isn't. :(

**Comment by pnowojski** [comment]
Why `Iteration` should be enough? If you have many invocation within one single iteration, this latch would have been reseted only once. Your code is equivalent of `tearDown` with `Invocation` level, but according to this scary java doc, `Level.Invocation` should be avoided - and yes, in our case it doesn't matter if you include the reset in the benchmark invocation.

**Review by pnowojski — APPROVED** [review]
LGTM % comment in the commit

**Comment by dawidwys** [comment]
After an offline discussion with Piotr, I realized I do not understand what an `Invocation` and an `Iteration` are. Piotr explained to me that within an `Invocation`, there might be multiple calls to the benchmarked method (`readFileSplit` in this case). If there are multiple invocations of the method within a single iteration, the second invocation did not have the latch properly reset, resulting in all records being emitted in the finishing stage of the `ContinuousFileReadingOperator`. This led to testing a different behaviour than the envisioned.

**Pull request merged**
