### PR TITLE
[FLINK-28931] Fix BlockingPartitionBenchmark compile error

### PR DESCRIPTION
**Pull request by rkhachatryan**

### CODE REVIEW

**Review by fredia — APPROVED** [review]

**Comment by fredia** [comment]
@reswqa would you like to take a look?

**Comment by rkhachatryan** [comment]
Sorry, just noticed the last message after merging. 
If there are any comments I'd be happy to address them in a separate PR then.

**Review by reswqa — COMMENTED** [review]
@rkhachatryan Thank you for fixing this problem, LGTM！

**Comment by rkhachatryan** [comment]
Thanks @reswqa and @fredia for the prompt review

**Pull request merged**
